### ISSUE TITLE
not support `shr` Instruction

### ISSUE THREAD

**Issue by ahfuzhang** [Maratyszcza/PeachPy#124]
python error info is:

```
Traceback (most recent call last):
  File "asm2asm.py", line 2169, in <module>
    main()
  File "asm2asm.py", line 2104, in main
    asm.parse(src, proto)
  File "asm2asm.py", line 2016, in parse
    self._parse(src)
  File "asm2asm.py", line 1888, in _parse
    self.code.instr(Instruction.parse(line))
  File "asm2asm.py", line 1692, in instr
    self.block.body.append(X86Instr(instr))
  File "asm2asm.py", line 1401, in __init__
    self.size  = instr.size
  File "asm2asm.py", line 636, in size
    return self.encoded_size(0)
  File "asm2asm.py", line 669, in encoded_size
    return len(self._instr(*list(self._encode_operands(True, offset))[::-1]).encode())
  File "/Library/Python/3.8/site-packages/peachpy/x86_64/generic.py", line 3303, in __init__
    raise SyntaxError("Instruction \"SHR\" requires 2 operands")
SyntaxError: Instruction "SHR" requires 2 operands

```

asm code like this:

```asm
_clz:                                   ## @clz
## %bb.0:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, %eax
	shrl	%eax
```

thanks.

**Comment by Maratyszcza** [comment]
Use `SHR(eax, 1)`
