### ISSUE TITLE
RETURN(physical) crashes when GeneralPurposeRegister is also used

### ISSUE THREAD

**Issue by pwaller** [Maratyszcza/PeachPy#65]
`RETURN(rax)` works fine by itself, but

```
with Function("crash", (), int64_t):
    r = GeneralPurposeRegister64()
    MOV(r, 999)
    RETURN(rax)
```

Crashes with:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/__main__.py", line 280, in <module>
    main()
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/__main__.py", line 267, in main
    execute_script(writers, options.input[0])
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/__main__.py", line 198, in execute_script
    execute_script(writers, source_filename)
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/__main__.py", line 198, in execute_script
    execute_script(writers, source_filename)
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/__main__.py", line 202, in execute_script
    exec(code, globals())
  File "summarize.py", line 35, in <module>
    RETURN(rax)
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/function.py", line 200, in __exit__
    abi_function = self.finalize(peachpy.x86_64.options.abi)
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/function.py", line 309, in finalize
    return ABIFunction(self, abi)
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/function.py", line 972, in __init__
    self._allocate_registers()
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/x86_64/function.py", line 1143, in _allocate_registers
    register_allocator.allocate_registers()
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/common/regalloc.py", line 80, in allocate_registers
    key=lambda reg: self._min_conflict_allocation_alternatives(virtual_id, reg))
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/common/regalloc.py", line 80, in <lambda>
    key=lambda reg: self._min_conflict_allocation_alternatives(virtual_id, reg))
  File "/home/pwaller/.local/lib/python3.5/site-packages/peachpy/common/regalloc.py", line 65, in _min_conflict_allocation_alternatives
    for conflict_internal_id in self.conflicting_registers[virtual_id]
ValueError: min() arg is an empty sequence
main.go:8: running "python3": exit status 1
```

**Comment by pwaller** [comment]
This also crashes, on the `RET` instruction with the same stack trace.

```
with Function("f", ()):
    r = GeneralPurposeRegister64()
    MOV(r, 1)
    MOV(r, [rdx])
    RET()
```

If you reorder the two `MOV` instructions or remove either one, it does not crash.
